import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import "@/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="h-screen grid grid-cols-[150px_1fr]">
          <aside className="border bg-card text-card-foreground shadow-2xl z-10"></aside>
          <div className="h-screen px-16 py-6 bg-green-50">
            <div className="h-full  z-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
