import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import "@/styles/globals.css";
import Avatar from "@/components/avatar";
import Navbar from "@/components/navbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        style={{ background: "#191923" }}
      >
        <div
          className="grid grid-cols-[350px_1fr_100px] gap-4 h-full px-16 pt-12"
          style={{
            background:
              "linear-gradient(159deg, rgba(37, 37, 50, 0.98), rgba(35, 35, 45, 0.98))",
          }}
        >
          <div className="">
            <Avatar />
          </div>
          <div className="overflow-y-auto hide-scrollbar">{children}</div>
          <div>
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
